version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: code has arrived
          command: |
            ls -al
            echo '***this should look familiar***'
      - run:
          name: Running in unique conatiner
          command: |
            node -v