version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest # Replace with your preferred Go version

    working_directory: /go/src/github.com/komal-gogi/Web-App

    steps:
      - checkout # Check out your code from your VCS (e.g., GitHub)

      - run:
          name: Setup Go
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/gorilla/mux
            dep ensure

      - run:
          name: Run Tests
          command: |
            go test -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build
